image: node:lts-slim

stages:
  - build
  - test
  - deploy
  - push_docker

default:
  before_script:
    - npm ci --include=dev

variables:
  DOCS_FOLDER: "documentation"
  SPEC_TO_DISPLAY: "openapi.json"
  DISABLE_TRY_IT_OUT_JS_METHOD: "const DisableTryItOutPlugin = function() {return {statePlugins:{spec:{wrapSelectors:{allowTryItOutFor:() => () => false}}}}}"
  DISABLE_TRY_IT_OUT_PLUGIN: ", DisableTryItOutPlugin"

npm:
  tags:
    - docker
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - packages/*/dist/

test:
  tags:
    - docker
  stage: test
  image: mcr.microsoft.com/playwright:v1.34.1-focal
  dependencies:
    - npm
  script:
    - npm test

invite_build:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  tags:
    - docker
  stage: push_docker
  before_script: []
  only:
    changes:
      - 'packages/matrix-invite/**/*'
    refs:
      - master@publicgroup/oss/twake/tom-server
  script:
    - echo "{\"auths\":{\"${DOCKERHUB_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKERHUB_USER}" "${DOCKERHUB_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/packages/matrix-invite/"
      --dockerfile "${CI_PROJECT_DIR}/packages/matrix-invite/Dockerfile"
      --destination "docker.io/twaketech/twake-matrix-invite:latest"

pages:
  tags:
    - docker
  stage: deploy
  rules:
    - if: '$CI_PROJECT_PATH == "publicgroup/oss/twake/tom-server" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npm run doc
    - mkdir public
    - cp -rp node_modules/swagger-ui-dist/* public
    - cp -rp $DOCS_FOLDER/* public
    - sed -i "/window\.onload\s=\sfunction()\s{/a $DISABLE_TRY_IT_OUT_JS_METHOD" public/swagger-initializer.js
    - sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#$SPEC_TO_DISPLAY#g" public/swagger-initializer.js
    - sed -i "/SwaggerUIBundle\.plugins\.DownloadUrl/a $DISABLE_TRY_IT_OUT_PLUGIN" public/swagger-initializer.js
  artifacts:
    paths:
      - public
