image: node:lts-slim

stages:
  - build
  - test

npm:
  tags:
    - ultralight
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  tags:
    - ultralight 
  stage: test
  dependencies:
    - npm
  script:
    - npm test
