image: node:lts-slim

stages:
  - build
  - test
  - push_docker

default:
  cache: &global_cache
    paths:
      - node_modules/

npm:
  tags:
    - docker
  stage: build
  script:
    - npm ci --include=dev
    - npm run build
  cache:
    <<: *global_cache
    policy: push
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - packages/*/dist/

test:
  tags:
    - docker
  stage: test
  image: mcr.microsoft.com/playwright:v1.32.0-focal
  cache:
    <<: *global_cache
    policy: pull
  dependencies:
    - npm
  script:
    - npm ci --include=dev
    - npm test

invite_build:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  tags:
    - docker
  stage: push_docker
  only:
    changes:
      - 'packages/matrix-invite/**/*'
    refs:
      - master@publicgroup/oss/twake/tom-server
  script:
    - echo "{\"auths\":{\"${DOCKERHUB_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${DOCKERHUB_USER}" "${DOCKERHUB_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/packages/matrix-invite/"
      --dockerfile "${CI_PROJECT_DIR}/packages/matrix-invite/Dockerfile"
      --destination "docker.io/twaketech/twake-matrix-invite:latest"
