image: node:lts-slim

stages:
  - build
  - test

default:
  cache: &global_cache
    paths:
      - node_modules/

npm:
  tags:
    - docker
  stage: build
  script:
    - npm ci
    - npm run build
  cache:
    <<: *global_cache
    policy: push
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - packages/*/dist/

test:
  tags:
    - docker
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  dependencies:
    - npm
  script:
    - npm test

invite_build:
  tags:
    - docker
  stage: build
  only:
    changes:
      - "packages/matrix-invite/**/*"
    refs:
      - master
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD $DOCKERHUB_REGISTRY
    - cd packages/matrix-invite
    - docker build -f Dockerfile --tag latest .
    - docker push latest
