# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: publish-tom-federation-server

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get all src files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            packages/federation-server/**/*
            .github/workflows/**
      - name: Publish to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: linagora/tom-federation-server
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          workdir: "${{ github.workspace }}"
          context: .
          buildoptions: "-t linagora/tom-federation-server -f packages/federation-server/Dockerfile"
          tags: "latest,${{ steps.date.outputs.date }}"
