on:
  push:
    branches: [ "tom-builds" ]

jobs:
  test:
    name: Build And Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  publish:
    name: Publish Federation Server
    uses: ./.github/workflows/publish-tom-federation-server.yml
    secrets: inherit